fix companyuser nova resource and model
tipoff/seo pull request #131
Opened 2021-05-05 05:33 UTC by arwaawan3

Closes #130

2021-05-05 19:08 UTC, joshtorres commented
Can you post a screenshot of this working please.

2021-05-05 19:08 UTC, joshtorres requested changes
Looks good but can you post a screenshot of this working please just to double check

2021-05-05 19:15 UTC, arwaawan3 commented
Oops I thought I did. My bad.
<img width="1266" alt="companyusers" src="https://user-images.githubusercontent.com/64331952/117196659-bfe35f80-adb4-11eb-8658-b713b0e95e7d.png">

2022-04-01 15:26 UTC, drewroberts approved these changes

2022-04-01 15:27 UTC, merged